@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
class(c1,core:InformationContentEntity)
class(c3,core:ComputingProcess)
class(c4,core:Agent)
class(c5,core:EncodedAlgorithm)
class(c6,ns:DataSet)
class(c7,core:MeasuredValueExpression)
class(c8,core:ValueExpression)
subClass(c6,c1)
subClass(c8,c1)
subClass(c7,c8)
individual(o1, ns1:air-temperature-value)
individual(o2, ns1:process-temperature-value)
individual(o3, ns1:rotational-speed-value)
individual(o4, ns1:torque-value)
individual(o5, ns1:tool-wear-value)
individual(o6, ns1:classification-result)
individual(o7, ns1:multilayerperceptron)
individual(o8, ns1:machine-learning-execution)
individual(o9, ns1:data-vector)
individual(o10, ns1:computer)
typeOf(o1, c7)
typeOf(o2, c7)
typeOf(o3, c7)
typeOf(o4, c7)
typeOf(o5, c7)
typeOf(o6, c8)
typeOf(o7, c5)
typeOf(o8, c3)
typeOf(o9, c6)
typeOf(o10, c4)

property(o1, bfo:continuantPartOf, o9, down)
property(o2, bfo:continuantPartOf, o9, down)
property(o3, bfo:continuantPartOf, o9, down)
property(o4, bfo:continuantPartOf, o9, down)
property(o5, bfo:continuantPartOf, o9, down)
property(o8, core:hasInput, o9)
property(o8, bfo:hasParticipant, o10)

property(o8, core:hasSpecifiedOutput, o6,right)
property(o7, bfo:isConcretizedBy, o8,down)
property(o7, bfo:genericallyDependsOn, o10,up)

@enduml
