@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
class(c1,iof:InformationContentEntity)
class(c2,iof:InformationContentEntity)
class(c3,iof:ComputingProcess)
class(c4,iof:Agent)
class(c5,iof:EncodedAlgorithm)

xSome(c5,bfo:genericallyDependsOn,c4,down)
xSome(c5,bfo:isConcretizedBy,c3,right)
xSome(c3,iof:hasSpecifiedOutput,c1,up)
xSome(c3,bfo:hasParticipant,c4,down)
xSome(c3,iof:hasInput,c2,right)

@enduml