@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml

oClass(bfo:Process)
oClass(bfo:TemporalInterval)
oClass(bfo:TemporalInstant)
oIndividual(ns1:launch-of-iphone)
typeOf(ns1:launch-of-iphone, bfo:Process)
oIndividual(ns1:launch-interval)
typeOf(ns1:launch-interval, bfo:TemporalInterval)
property(ns1:launch-of-iphone, iof:occupiesTemporalRegion, ns1:launch-interval, down)
oIndividual(ns1:launch-start-time)
typeOf(ns1:launch-start-time, bfo:TemporalInstant)
property(ns1:launch-interval, bfo:hasFirstInstant, ns1:launch-start-time, down)

oClass(ns:GPSTimeDescription)
oClass(time:GeneralDateTimeDescription)
subClass(ns:GPSTimeDescription, time:GeneralDateTimeDescription)
xSomeData(ns:GPSTimeDescription, time:second, rdfs:Literal, "[1]", right)
xSomeData(ns:GPSTimeDescription, time:week, rdfs:Literal, "[1]", right)
xSomeData(ns:GPSTimeDescription, time:unitType, time:unitSecond, "", down)
oClass(ns:GPSTimeSystem)
xSome(ns:GPSTimeDescription, time:hasTRS, ns:GPSTimeSystem, "", left)

oIndividual(ns1:time-instant-expression1)
typeOf(ns1:time-instant-expression1, ns:GPSTimeDescription)
property(ns1:launch-start-time, iof:hasValueExpressionAtAllTimes, ns1:time-instant-expression1, right)
data(ns1:time-instant-expression1, time:week, 1430)
data(ns1:time-instant-expression1, time:second, 324018)
@enduml