@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml

oClass(bfo:Process)
oClass(bfo:TemporalInterval)
oClass(bfo:TemporalInstant)
oIndividual(ns1:launch-of-iphone)
typeOf(ns1:launch-of-iphone, bfo:Process)
oIndividual(ns1:launch-interval)
typeOf(ns1:launch-interval, bfo:TemporalInterval)
property(ns1:launch-of-iphone, iof:occupiesTemporalRegion, ns1:launch-interval, right)
oIndividual(ns1:launch-start-time)
typeOf(ns1:launch-start-time, bfo:TemporalInstant)
property(ns1:launch-interval, bfo:hasFirstInstant, ns1:launch-start-time, down)

oIndividual(ns1:time-instant-expression1)
oClass(time:DateTimeDescription)
typeOf(ns1:time-instant-expression1, time:DateTimeDescription)
property(ns1:launch-start-time, iof:hasValueExpressionAtAllTimes, ns1:time-instant-expression1, down)
oIndividual(time:Friday)
oClass(time:DayOfWeek)
typeOf(time:Friday, time:DayOfWeek)
property(ns1:time-instant-expression1, time:dayOfWeek, time:Friday, down)

oIndividual(ns1:time-instant-expression2)
typeOf(ns1:time-instant-expression2, time:DateTimeDescription)
property(ns1:launch-start-time, iof:hasValueExpressionAtAllTimes, ns1:time-instant-expression2, down)
data(ns1:time-instant-expression2, time:month, --06^^xsd:gMonth)

oIndividual(ns1:time-instant-expression3)
oClass(iof:TemporalInstantValueExpression)
typeOf(ns1:time-instant-expression3, iof:TemporalInstantValueExpression)
property(ns1:launch-start-time, iof:hasValueExpressionAtAllTimes, ns1:time-instant-expression3, down)
data(ns1:time-instant-expression3, iof:hasDateTimeInstantValue, 2007-06-29T18:00:00Z)


@enduml