@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
oClass(iof:TemporalDurationValueExpression)
oClass(bfo:TemporalInterval)
xSome(iof:TemporalDurationValueExpression, iof:isValueExpressionOfAtAllTimes, bfo:TemporalInterval, "", up)
oClass(time:TemporalDuration)
equivalent(iof:TemporalDurationValueExpression, time:TemporalDuration, right)
oClass(time:GeneralDurationDescription)
subClass(time:GeneralDurationDescription, time:TemporalDuration)
oClass(time:TemporalUnit)
xSome(time:GeneralDurationDescription, time:unitType, time:TemporalUnit, "", down)
oClass(time:TRS)
xOnly(time:GeneralDurationDescription, time:hasTRS, time:TRS, " ", right)
xOnlyData(time:GeneralDurationDescription, time:years, xsd:decimal)
xOnlyData(time:GeneralDurationDescription, time:months, xsd:decimal)
xOnlyData(time:GeneralDurationDescription, time:days, xsd:decimal)
xOnlyData(time:GeneralDurationDescription, time:hours, xsd:decimal)
xOnlyData(time:GeneralDurationDescription, time:minutes, xsd:decimal)
xOnlyData(time:GeneralDurationDescription, time:seconds, xsd:decimal)
oClass(time:Duration)
subClass(time:Duration, time:TemporalDuration)
xSomeData(time:Duration, time:numericDuration, xsd:decimal, "[1]", right)
xSome(time:Duration, time:unitType, time:TemporalUnit, "[1]", right)
@enduml