@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/main/nowl/profiles/iof.iuml
individual(i1, ns1:firstInstant_0, bfo:TemporalInstant)
individual(i2, ns1:firstVE_0, iof:TemporalInstantValueExpression)
individual(i3, ns1:firstInstant_2, bfo:TemporalInstant)
individual(i4, ns1:firstVE_2, iof:TemporalInstantValueExpression)
individual(i5, ns1:firstInstant_4, bfo:TemporalInstant)
individual(i6, ns1:firstVE_4, iof:TemporalInstantValueExpression)
individual(i7, ns1:interval_0, bfo:TemporalInterval)
individual(i8, ns1:lastInstant_0, bfo:TemporalInstant)
individual(i9, ns1:interval_2, bfo:TemporalInterval)
individual(i10, ns1:lastInstant_2, bfo:TemporalInstant)
individual(i11, ns1:interval_4, bfo:TemporalInterval)
individual(i12, ns1:lastInstant_4, bfo:TemporalInstant)
individual(i13, ns1:lastVE_0, iof:TemporalInstantValueExpression)
individual(i14, ns1:lastVE_2, iof:TemporalInstantValueExpression)
individual(i15, ns1:lastVE_4, iof:TemporalInstantValueExpression)
xIndividual(i16, ns1:process_0, '["bfo:process", "ns2:HeatWater"]')
xIndividual(i17, ns1:process_2, '["bfo:process", "ns2:SoakCoffee"]')
xIndividual(i18, ns1:process_4, '["bfo:process", "ns2:HeatCarafe"]')
property(i1, iof:has value expression at all times, i2, down)
property(i1, bfo:first instant of, i7, u)
data(i2, iof:has date-time instant value, "2025-02-21 07:08:00")
property(i3, iof:has value expression at all times, i4, down)
property(i3, bfo:first instant of, i9, u)
data(i4, iof:has date-time instant value, "2025-02-21 07:08:02")
property(i5, iof:has value expression at all times, i6, down)
property(i5, bfo:first instant of, i11, u)
data(i6, iof:has date-time instant value, "2025-02-21 07:08:04")
property(i7, bfo:has last instant, i8, down)
property(i8, iof:has value expression at all times, i13, down)
property(i9, bfo:has last instant, i10, down)
property(i10, iof:has value expression at all times, i14, down)
property(i11, bfo:has last instant, i12, down)
property(i12, iof:has value expression at all times, i15, down)
data(i13, iof:has date-time instant value, "2025-02-21 07:08:02")
data(i14, iof:has date-time instant value, "2025-02-21 07:08:04")
property(i16, bfo:occupies temporal region, i7, down)
property(i17, bfo:occupies temporal region, i9, down)
property(i18, bfo:occupies temporal region, i11, down)
property(i16, bfo:precedes, i17)
property(i17, bfo:precedes, i18)
@enduml